### PR TITLE
Replaces `||` syntax error with `fetch`

### PR DESCRIPTION
**Pull request by baweaver**
Noticed a syntax error, replaced with `fetch`

### CODE REVIEW

**Review by kellysutton — APPROVED** [review]
👍

**Review by kellysutton — APPROVED** [review]

**Review by alexevanczuk — COMMENTED** [review]
@baweaver This seems fine but I don't see the syntax error. Can you elaborate?

**Comment by baweaver** [comment]
```ruby
irb(main):001:0> something = { a: 1 }
=> {:a=>1}

irb(main):002:0> something[:a] || raise "issue"
SyntaxError ((irb):2: syntax error, unexpected string literal, expecting `do' or '{' or '(')
something[:a] || raise "issue"
                       ^
irb(main):003:0> something[:b] || raise "issue"
SyntaxError ((irb):3: syntax error, unexpected string literal, expecting `do' or '{' or '(')
something[:b] || raise "issue"
```

**Comment by baweaver** [comment]
It'll crash if no parens are used, so this will _technically_ work but with the popularity of no-parens it's possible to break it.

**Comment by AlexEvanczuk** [comment]
Sorry I'm a bit confused -- since parens are used, how is it possible to break? Or are we saying that it would be a bug if we changed the syntax and we just wanted to be defensive against that?

Whatever works for me, I just want to make sure we keep a human readable error message (which we lose when we use `fetch` which leaks more of the private implementation.

**Pull request closed without merging**
